version: "3.9"

services:
  streamlit:
    container_name: dashboard
    build:
      context: .
    restart: always
    volumes:
      - ./weatherdashboard:/app/weatherdashboard/
      - ./data:/app/data/
      - .streamlit:/app/.streamlit/
    command: ["streamlit", "run", "weatherdashboard/00_🏠_Home.py"]
    environment:
      - BASE_URL=$BASE_URL
      - API_KEY=$API_KEY

    ports:
      - 8501:8501
    stdin_open: true
    tty: true
